import type { NextPage } from "next";
import Head from "next/head";
import { adminList } from "../data/adminList";
import List from "../components/List/List";

const Home: NextPage = () => {
  return (
    <div className="p-4">
      <Head>
        <title>Komo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="text-2xl font-bold text-center rounded-xl border-2 border-teal-600">
          Komon Creator Dashboard
          <div className="mt-16">
            {adminList.map((item, index) => {
              return <List key={index} item={item} />;
            })}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
